// @ts-nocheck
// GENERATED by `npm run build:functions` from src/server/shortcuts and src/domain. Do not edit by hand.
// The Four Burners shortcuts Edge Function: Siri and Apple Shortcuts logging, and Apple Health data.
// Deploy: README.
//#region src/server/env.ts
function serviceKeyFrom(env, override) {
	const explicit = env(override);
	if (explicit) return explicit;
	try {
		const keys = JSON.parse(env("SUPABASE_SECRET_KEYS") ?? "{}");
		const k = keys.default ?? Object.values(keys)[0];
		if (typeof k === "string" && k) return k;
	} catch {}
	return env("SUPABASE_SERVICE_ROLE_KEY") || void 0;
}
//#endregion
//#region src/domain/types.ts
const DEFAULT_NOTIFY_PREFS = {
	daily: {
		on: true,
		time: "20:00"
	},
	weekly: {
		on: true,
		time: "17:00"
	},
	nudges: true,
	quiet: {
		on: true,
		start: "22:00",
		end: "07:00"
	}
};
const DEFAULT_SETTINGS = {
	dayBoundaryHour: 3,
	graceDaysPerWeek: 1,
	soundEffects: true,
	haptics: true,
	reviewDay: 6,
	sensitiveTerms: [],
	notify: DEFAULT_NOTIFY_PREFS
};
//#endregion
//#region src/domain/config.ts
const INTENT_EXPECTATION = {
	high: 1,
	steady: .85,
	low: .6
};
const PACE_THRESHOLDS = {
	onTrack: .9,
	behind: .6
};
const CRUNCH_EXPECTATION = .25;
//#endregion
//#region src/domain/dates.ts
const DAY_MS = 864e5;
function toUtcMs(d) {
	const [y, m, day] = d.split("-").map(Number);
	return Date.UTC(y, m - 1, day);
}
function fromUtcMs(ms) {
	return new Date(ms).toISOString().slice(0, 10);
}
function addDays(d, n) {
	return fromUtcMs(toUtcMs(d) + n * DAY_MS);
}
function diffDays(a, b) {
	return Math.round((toUtcMs(b) - toUtcMs(a)) / DAY_MS);
}
function dateRange(a, b) {
	const out = [];
	for (let d = a; d <= b; d = addDays(d, 1)) out.push(d);
	return out;
}
function localDateFor(instant, offsetMin, dayBoundaryHour) {
	const shifted = instant.getTime() + offsetMin * 6e4 - dayBoundaryHour * 36e5;
	return fromUtcMs(Math.floor(shifted / DAY_MS) * DAY_MS);
}
function quarterOf(d) {
	return quarterSpan(`${Number(d.slice(0, 4))}-Q${Math.floor((Number(d.slice(5, 7)) - 1) / 3) + 1}`);
}
function quarterSpan(id) {
	const [ys, qs] = id.split("-Q");
	const y = Number(ys);
	const q = Number(qs);
	const startMonth = (q - 1) * 3 + 1;
	return {
		id,
		start: `${y}-${String(startMonth).padStart(2, "0")}-01`,
		end: addDays(q === 4 ? `${y + 1}-01-01` : `${y}-${String(startMonth + 3).padStart(2, "0")}-01`, -1)
	};
}
//#endregion
//#region src/domain/goals.ts
const MONTH_DAYS = 365.25 / 12;
function windowDays(goal) {
	return Math.max(1, diffDays(goal.startDate, goal.deadline) + 1);
}
function requiredFor(goal) {
	switch (goal.type) {
		case "number": return Math.max(0, goal.target ?? 0);
		case "habit": {
			const perPeriod = Math.max(0, goal.target ?? 0);
			const periodDays = goal.habitPeriod === "month" ? MONTH_DAYS : 7;
			return Math.max(perPeriod > 0 ? 1 : 0, Math.round(perPeriod * windowDays(goal) / periodDays));
		}
		case "yesno": return 1;
		case "milestone": return goal.milestones?.length ?? 0;
	}
}
function actualFor(goal, logs) {
	const mine = logs.filter((l) => l.goalId === goal.id && !l.deleted);
	switch (goal.type) {
		case "number":
		case "habit": return mine.reduce((s, l) => s + l.value, 0);
		case "yesno": return mine.some((l) => l.value > 0) ? 1 : 0;
		case "milestone": {
			const done = new Set(mine.map((l) => l.milestoneId).filter(Boolean));
			return goal.milestones?.filter((m) => done.has(m.id)).length ?? 0;
		}
	}
}
function elapsedFraction(goal, today, crunchDates) {
	if (today < goal.startDate) return 0;
	const total = windowDays(goal);
	if (today > goal.deadline) return weightedDays(goal.startDate, goal.deadline, crunchDates) / total;
	const beforeToday = today > goal.startDate ? weightedDays(goal.startDate, addDays(today, -1), crunchDates) : 0;
	const todayWeight = crunchDates?.has(today) ? CRUNCH_EXPECTATION : 1;
	return Math.min(1, (beforeToday + .5 * todayWeight) / total);
}
function weightedDays(a, b, crunch) {
	if (b < a) return 0;
	if (!crunch || crunch.size === 0) return diffDays(a, b) + 1;
	let sum = 0;
	for (const d of dateRange(a, b)) sum += crunch.has(d) ? CRUNCH_EXPECTATION : 1;
	return sum;
}
function shapeExpectation(type, elapsed) {
	return type === "yesno" ? elapsed * elapsed : elapsed;
}
function goalProgress(goal, logs, today, ctx) {
	const required = requiredFor(goal);
	const actual = actualFor(goal, logs);
	const fraction = required > 0 ? Math.min(1, actual / required) : 0;
	const complete = required > 0 && actual >= required;
	const elapsed = elapsedFraction(goal, today, ctx.crunchDates);
	const expected = shapeExpectation(goal.type, elapsed) * INTENT_EXPECTATION[ctx.intent];
	let pace;
	if (complete) pace = 1;
	else if (expected < .02 || diffDays(goal.startDate, today) < 2) pace = 1;
	else pace = Math.min(1, fraction / expected);
	const status = complete ? "done" : pace >= PACE_THRESHOLDS.onTrack ? "on_track" : pace >= PACE_THRESHOLDS.behind ? "behind" : "slipping";
	return {
		actual,
		required,
		fraction,
		expected,
		pace,
		status,
		complete
	};
}
new Set("four burners burner coach packet end of family friends health work high steady low suggested actions action type week weekly review quarter crunch me why when pace active trimmed redacted progress consistency streak energy days day wins misses notes note people goals goal draft last prior off track ask load now done yes no travel life theme people setup check in about the and a".split(" "));
//#endregion
//#region src/domain/notify.ts
const TIME_RE = /^([01]\d|2[0-3]):([0-5]\d)$/;
function parseTime(s) {
	const m = typeof s === "string" ? TIME_RE.exec(s) : null;
	return m ? Number(m[1]) * 60 + Number(m[2]) : null;
}
const bool = (v, d) => typeof v === "boolean" ? v : d;
const time = (v, d) => parseTime(v) === null ? d : v;
function reminder(v, d) {
	const r = v && typeof v === "object" ? v : {};
	return {
		on: bool(r.on, d.on),
		time: time(r.time, d.time)
	};
}
function notifyPrefsOf(settings) {
	const n = settings?.notify ?? {};
	const d = DEFAULT_NOTIFY_PREFS;
	const q = n.quiet && typeof n.quiet === "object" ? n.quiet : {};
	return {
		daily: reminder(n.daily, d.daily),
		weekly: reminder(n.weekly, d.weekly),
		nudges: bool(n.nudges, d.nudges),
		quiet: {
			on: bool(q.on, d.quiet.on),
			start: time(q.start, d.quiet.start),
			end: time(q.end, d.quiet.end)
		}
	};
}
function settingsOf(value) {
	const v = value && typeof value === "object" ? value : {};
	const d = DEFAULT_SETTINGS;
	const int = (x, lo, hi, def) => typeof x === "number" && Number.isInteger(x) && x >= lo && x <= hi ? x : def;
	return {
		...d,
		dayBoundaryHour: int(v.dayBoundaryHour, 0, 23, d.dayBoundaryHour),
		graceDaysPerWeek: int(v.graceDaysPerWeek, 0, 7, d.graceDaysPerWeek),
		reviewDay: int(v.reviewDay, 0, 6, d.reviewDay),
		sensitiveTerms: Array.isArray(v.sensitiveTerms) ? v.sensitiveTerms.filter((t) => typeof t === "string") : [],
		notify: notifyPrefsOf(v)
	};
}
function isValidTimeZone(tz) {
	if (typeof tz !== "string" || !tz || tz.length > 64) return false;
	try {
		new Intl.DateTimeFormat("en-US", { timeZone: tz });
		return true;
	} catch {
		return false;
	}
}
function zoneOffsetMin(now, timeZone) {
	if (!isValidTimeZone(timeZone)) return 0;
	const parts = new Intl.DateTimeFormat("en-US", {
		timeZone,
		hourCycle: "h23",
		year: "numeric",
		month: "numeric",
		day: "numeric",
		hour: "numeric",
		minute: "numeric",
		second: "numeric"
	}).formatToParts(now);
	const get = (t) => Number(parts.find((p) => p.type === t)?.value ?? 0);
	const asUtc = Date.UTC(get("year"), get("month") - 1, get("day"), get("hour") % 24, get("minute"), get("second"));
	return Math.round((asUtc - Math.floor(now.getTime() / 1e3) * 1e3) / 6e4);
}
//#endregion
//#region src/domain/shortcuts.ts
const FILLER = new Set([
	"my",
	"the",
	"a",
	"an",
	"goal",
	"to",
	"for"
]);
function nameWords(s) {
	const words = s.normalize("NFKD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/['’]/g, "").replace(/&/g, " and ").split(/[^\p{L}\p{N}]+/u).filter(Boolean);
	const kept = words.filter((w) => !FILLER.has(w));
	return kept.length ? kept : words;
}
function matchByName(items, query, nameOf) {
	const q = nameWords(query);
	if (!q.length) return { kind: "none" };
	const qs = q.join(" ");
	const named = items.map((item) => ({
		item,
		w: nameWords(nameOf(item))
	})).filter((x) => x.w.length);
	const tests = [
		(w) => w.join(" ") === qs,
		(w) => {
			const s = w.join(" ");
			return s.startsWith(`${qs} `) || qs.startsWith(`${s} `);
		},
		(w) => q.every((x) => w.some((y) => y === x || x.length >= 3 && y.startsWith(x))),
		(w) => w.every((y) => q.includes(y))
	];
	for (const test of tests) {
		const hits = named.filter((x) => test(x.w)).map((x) => x.item);
		if (hits.length === 1) return {
			kind: "match",
			item: hits[0]
		};
		if (hits.length > 1) return {
			kind: "ambiguous",
			items: hits
		};
	}
	return { kind: "none" };
}
const ISO_WITH_OFFSET = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2})(?:[.,]\d+)?)?\s*(Z|[+-]\d{2}:?\d{2})$/;
function parseAt(at) {
	const m = typeof at === "string" ? ISO_WITH_OFFSET.exec(at.trim()) : null;
	if (!m) return null;
	let offsetMin = 0;
	if (m[7] !== "Z") {
		const sign = m[7][0] === "-" ? -1 : 1;
		const digits = m[7].slice(1).replace(":", "");
		offsetMin = sign * (Number(digits.slice(0, 2)) * 60 + Number(digits.slice(2)));
		if (Math.abs(offsetMin) > 840) return null;
	}
	const ms = Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +(m[6] ?? 0)) - offsetMin * 6e4;
	if (!Number.isFinite(ms)) return null;
	return {
		instant: new Date(ms),
		offsetMin
	};
}
const AT_MAX_PAST_MS = 6048e5;
const AT_MAX_FUTURE_MS = 864e5;
function stampFor(at, dayBoundaryHour, fallbackOffsetMin, now) {
	const p = parseAt(at);
	const ok = p && p.instant.getTime() >= now.getTime() - AT_MAX_PAST_MS && p.instant.getTime() <= now.getTime() + AT_MAX_FUTURE_MS;
	const instant = ok ? p.instant : now;
	const offsetMin = ok ? p.offsetMin : fallbackOffsetMin;
	return {
		at: instant.toISOString(),
		offsetMin,
		localDate: localDateFor(instant, offsetMin, dayBoundaryHour)
	};
}
function parseAmount(v) {
	const n = typeof v === "number" ? v : typeof v === "string" && v.trim() ? Number(v.trim().replace(/,(?=\d{3}\b)/g, "").replace(",", ".")) : NaN;
	return Number.isFinite(n) && n > 0 && n < 1e7 ? Math.round(n * 100) / 100 : null;
}
function parseTouchType(v) {
	const s = typeof v === "string" ? v.toLowerCase().replace(/[^a-z]+/g, " ").trim() : "";
	if (/\b(call|called|phone|facetime|rang)\b/.test(s)) return "call";
	if (/\b(text|texted|message|messaged|imessage|whatsapp|sms|email)\b/.test(s)) return "text";
	if (/\b(in ?person|inperson|saw|met|visit|visited|dinner|lunch|coffee)\b/.test(s)) return "in_person";
	return "other";
}
const TOUCH_LABEL = {
	call: "call",
	text: "text",
	in_person: "time in person",
	other: "connection"
};
function formatAmount(n) {
	return new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(n);
}
function planLog(goal, amount) {
	if (goal.type === "milestone") return {
		ok: false,
		message: `"${goal.title}" has steps. Check off the next step in the app.`
	};
	if (goal.type === "number") {
		const value = parseAmount(amount);
		if (value === null) return {
			ok: false,
			message: `How much for "${goal.title}"? Send an amount${goal.unit ? ` in ${goal.unit}` : ""}.`
		};
		return {
			ok: true,
			value,
			source: "shortcut"
		};
	}
	if (goal.type === "habit") {
		const n = parseAmount(amount);
		return {
			ok: true,
			value: n && Number.isInteger(n) && n <= 20 ? n : 1,
			source: "shortcut"
		};
	}
	return {
		ok: true,
		value: 1,
		source: "shortcut"
	};
}
function logReply(goal, value, logs, today, intent) {
	const p = goalProgress(goal, logs, today, { intent });
	const title = goal.title;
	if (goal.type === "yesno") return `Marked "${title}" done. Nice work.`;
	return `Logged ${goal.type === "number" ? `${formatAmount(value)}${goal.unit ? ` ${goal.unit}` : ""} to ` : ""}"${title}".${p.required > 0 ? ` ${formatAmount(p.actual)} of ${formatAmount(p.required)}${p.complete ? ". Goal complete!" : " so far."}` : ""}`;
}
function touchReply(person, type) {
	return `Logged a ${TOUCH_LABEL[type]} with ${person.name}.`;
}
function notFoundReply(kind, query, candidates) {
	const what = kind === "goal" ? "goal" : "person";
	if (!candidates.length) return kind === "goal" ? "You have no goals this quarter yet." : "You have no key people yet.";
	const list = candidates.slice(0, 6).join(", ");
	return `No ${what} matches "${query.trim().slice(0, 60)}". Try one of: ${list}.`;
}
function ambiguousReply(query, names) {
	return `"${query.trim().slice(0, 60)}" could be ${names.slice(0, 4).join(" or ")}. Say a little more of the name.`;
}
const HEALTH_METRICS = {
	steps: {
		label: "Steps",
		unit: "steps",
		defaultMin: 8e3,
		max: 2e5
	},
	workouts: {
		label: "Workouts",
		unit: "workouts",
		defaultMin: 1,
		max: 20
	},
	activeMinutes: {
		label: "Exercise minutes",
		unit: "minutes",
		defaultMin: 30,
		max: 1440
	},
	sleepHours: {
		label: "Sleep",
		unit: "hours",
		defaultMin: 7,
		max: 24
	}
};
const HEALTH_METRIC_IDS = Object.keys(HEALTH_METRICS);
function readHealthDay(body) {
	const out = {};
	const raw = {
		steps: body.steps,
		workouts: body.workouts,
		activeMinutes: body.activeMinutes ?? body.exerciseMinutes,
		sleepHours: body.sleepHours ?? (parseAmount(body.sleepMinutes) !== null ? parseAmount(body.sleepMinutes) / 60 : parseAmount(body.sleepSeconds) !== null ? parseAmount(body.sleepSeconds) / 3600 : void 0)
	};
	for (const m of HEALTH_METRIC_IDS) {
		const n = raw[m] === 0 || raw[m] === "0" ? 0 : parseAmount(raw[m]);
		if (n === null || n > HEALTH_METRICS[m].max) continue;
		out[m] = m === "sleepHours" ? Math.round(n * 10) / 10 : Math.round(n);
	}
	return out;
}
const healthLogId = (goalId, date) => `health-${goalId}-${date}`;
function canLinkHealth(goal) {
	return goal.burner === "health" && goal.type !== "milestone";
}
function planHealthLogs(goals, day, date, loggedByHand = new Set()) {
	const out = [];
	for (const goal of goals) {
		const link = goal.health;
		if (goal.deleted || !link || !canLinkHealth(goal) || !(link.metric in HEALTH_METRICS)) continue;
		if (date < goal.startDate || date > goal.deadline) continue;
		const amount = day[link.metric];
		if (amount === void 0 || amount <= 0) continue;
		if (goal.type !== "number" && loggedByHand.has(goal.id)) continue;
		const value = goal.type === "number" ? amount : amount >= (link.min ?? HEALTH_METRICS[link.metric].defaultMin) ? 1 : 0;
		if (value > 0) out.push({
			goal,
			id: healthLogId(goal.id, date),
			value,
			amount
		});
	}
	return out;
}
function healthDate(v, today) {
	if (typeof v !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(v.trim())) return today;
	const d = v.trim();
	return d <= addDays(today, 1) && d >= addDays(today, -7) ? d : today;
}
function healthReply(applied, day, date) {
	if (!HEALTH_METRIC_IDS.filter((m) => day[m] !== void 0).length) return "No Health numbers came through. Check the Shortcut sends steps, workouts, activeMinutes or sleepHours.";
	if (!applied.length) return `Got Health data for ${date}. No linked goal needed it today.`;
	return `Health for ${date}: ${applied.map((a) => a.goal.type === "number" ? `${formatAmount(a.value)} ${HEALTH_METRICS[a.goal.health.metric].unit} to "${a.goal.title}"` : `"${a.goal.title}" counted`).join("; ")}.`;
}
new TextEncoder();
//#endregion
//#region src/shortcuts/token.ts
const TOKEN_RE = /^fb_[A-Za-z0-9_-]{43}$/;
function isTokenFormat(s) {
	return typeof s === "string" && TOKEN_RE.test(s);
}
async function hashToken(token) {
	const digest = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(token)));
	return Array.from(digest, (b) => b.toString(16).padStart(2, "0")).join("");
}
//#endregion
//#region src/server/shortcuts/handler.ts
function reply(status, body) {
	return new Response(JSON.stringify(body), {
		status,
		headers: { "Content-Type": "application/json; charset=utf-8" }
	});
}
const MAX_BODY = 8192;
const BAD_TOKEN = "This Shortcut token is wrong or was revoked. Make a new one in Four Burners: Settings > Shortcuts and Siri.";
const text = (v, max) => typeof v === "string" && v.trim() ? v.trim().slice(0, max) : void 0;
function nextUpdatedAt(now, prev) {
	const p = prev ? Date.parse(prev) : NaN;
	return new Date(Number.isFinite(p) && p >= now.getTime() ? p + 1 : now.getTime()).toISOString();
}
async function stamp(ctx) {
	const [settingsValue, tz] = await Promise.all([ctx.deps.store.settings(ctx.userId), ctx.deps.store.latestTimeZone(ctx.userId)]);
	const settings = settingsOf(settingsValue);
	const fallback = tz && isValidTimeZone(tz) ? zoneOffsetMin(ctx.now, tz) : 0;
	return {
		stamp: stampFor(ctx.body.at, settings.dayBoundaryHour, fallback, ctx.now),
		settings
	};
}
const loggable = (g) => !g.deleted && g.type !== "milestone";
async function listGoals(ctx) {
	const { stamp: s } = await stamp(ctx);
	const goals = (await ctx.deps.store.goals(ctx.userId, quarterOf(s.localDate).id)).filter(loggable);
	const order = [
		"family",
		"friends",
		"health",
		"work"
	];
	const items = goals.sort((a, b) => order.indexOf(a.burner) - order.indexOf(b.burner) || a.order - b.order).map((g) => g.title);
	return {
		ok: true,
		message: items.length ? `${items.length} goals.` : "You have no goals this quarter yet.",
		items
	};
}
async function listPeople(ctx) {
	const people = (await ctx.deps.store.people(ctx.userId)).filter((p) => !p.deleted).sort((a, b) => a.order - b.order);
	return {
		ok: true,
		message: people.length ? `${people.length} people.` : "You have no key people yet.",
		items: people.map((p) => p.name)
	};
}
async function logGoal(ctx) {
	const query = text(ctx.body.goal, 120);
	if (!query) return {
		ok: false,
		message: "Which goal? Send its name as \"goal\"."
	};
	const { stamp: s } = await stamp(ctx);
	const quarterId = quarterOf(s.localDate).id;
	const [goals, quarter] = await Promise.all([ctx.deps.store.goals(ctx.userId, quarterId), ctx.deps.store.quarter(ctx.userId, quarterId)]);
	const live = goals.filter((g) => !g.deleted);
	const m = matchByName(live, query, (g) => g.title);
	if (m.kind === "none") return {
		ok: false,
		message: notFoundReply("goal", query, live.filter(loggable).map((g) => g.title))
	};
	if (m.kind === "ambiguous") return {
		ok: false,
		message: ambiguousReply(query, m.items.map((g) => g.title))
	};
	const goal = m.item;
	const plan = planLog(goal, ctx.body.value);
	if (!plan.ok) return {
		ok: false,
		message: plan.message
	};
	const note = text(ctx.body.note, 500);
	const entry = {
		id: ctx.deps.newId(),
		goalId: goal.id,
		value: plan.value,
		...s,
		createdAt: s.at,
		updatedAt: nextUpdatedAt(ctx.now),
		source: "shortcut",
		...note ? {
			note,
			notePrivate: false
		} : {}
	};
	await ctx.deps.store.put(ctx.userId, "logs", entry);
	const logs = [...(await ctx.deps.store.logsForGoal(ctx.userId, goal.id)).filter((l) => l.id !== entry.id), entry];
	return {
		ok: true,
		message: logReply(goal, plan.value, logs, s.localDate, quarter?.intents?.[goal.burner] ?? "steady")
	};
}
async function logTouch(ctx) {
	const query = text(ctx.body.person, 120);
	if (!query) return {
		ok: false,
		message: "Who? Send their name as \"person\"."
	};
	const people = (await ctx.deps.store.people(ctx.userId)).filter((p) => !p.deleted);
	const m = matchByName(people, query, (p) => p.name);
	if (m.kind === "none") return {
		ok: false,
		message: notFoundReply("person", query, people.map((p) => p.name))
	};
	if (m.kind === "ambiguous") return {
		ok: false,
		message: ambiguousReply(query, m.items.map((p) => p.name))
	};
	const { stamp: s } = await stamp(ctx);
	const type = parseTouchType(ctx.body.type);
	const note = text(ctx.body.note, 500);
	const tp = {
		id: ctx.deps.newId(),
		personId: m.item.id,
		type,
		...s,
		createdAt: s.at,
		updatedAt: nextUpdatedAt(ctx.now),
		source: "shortcut",
		...note ? {
			note,
			notePrivate: false
		} : {}
	};
	await ctx.deps.store.put(ctx.userId, "touchpoints", tp);
	return {
		ok: true,
		message: touchReply(m.item, type)
	};
}
async function applyHealth(ctx) {
	const day = readHealthDay(ctx.body);
	const { stamp: s } = await stamp(ctx);
	const date = healthDate(ctx.body.date, s.localDate);
	const goals = await ctx.deps.store.goals(ctx.userId, quarterOf(date).id);
	const byHand = new Set();
	for (const g of goals) {
		if (g.deleted || !g.health || g.type === "number") continue;
		if ((await ctx.deps.store.logsForGoal(ctx.userId, g.id)).some((l) => !l.deleted && l.localDate === date && l.source !== "health")) byHand.add(g.id);
	}
	const plans = planHealthLogs(goals, day, date, byHand);
	const applied = [];
	for (const p of plans) {
		const existing = await ctx.deps.store.get(ctx.userId, "logs", p.id);
		if (existing?.deleted || existing?.data?.deleted) continue;
		if (existing && existing.data.healthWrittenAt !== existing.updated_at) continue;
		applied.push(p);
		if (existing && existing.data.value === p.value) continue;
		const updatedAt = nextUpdatedAt(ctx.now, existing?.updated_at);
		const entry = {
			...existing?.data ?? {},
			id: p.id,
			goalId: p.goal.id,
			value: p.value,
			at: s.at,
			offsetMin: s.offsetMin,
			localDate: date,
			createdAt: existing?.data?.createdAt ?? s.at,
			updatedAt,
			source: "health",
			healthWrittenAt: updatedAt
		};
		if (!await ctx.deps.store.put(ctx.userId, "logs", entry)) applied.pop();
	}
	return {
		ok: HEALTH_METRIC_IDS.some((m) => day[m] !== void 0),
		message: healthReply(applied, day, date)
	};
}
function createShortcutsHandler(deps) {
	return async (req) => {
		if (req.method !== "POST") return reply(405, {
			ok: false,
			message: "Use POST."
		});
		const token = /^Bearer\s+(\S+)$/i.exec(req.headers.get("authorization") ?? "")?.[1];
		if (!isTokenFormat(token)) return reply(401, {
			ok: false,
			message: BAD_TOKEN
		});
		try {
			const found = await deps.store.tokenByHash(await hashToken(token));
			if (!found) return reply(401, {
				ok: false,
				message: BAD_TOKEN
			});
			const raw = await req.text();
			if (raw.length > MAX_BODY) return reply(413, {
				ok: false,
				message: "That request is too large."
			});
			let body = {};
			try {
				const parsed = raw.trim() ? JSON.parse(raw) : {};
				if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) body = parsed;
			} catch {
				return reply(400, {
					ok: false,
					message: "The Shortcut must send a JSON body."
				});
			}
			const now = deps.now();
			deps.store.markTokenUsed(found.id, now.toISOString()).catch(() => void 0);
			const ctx = {
				deps,
				userId: found.userId,
				body,
				now
			};
			const action = typeof body.action === "string" ? body.action.toLowerCase() : "ping";
			switch (action) {
				case "ping": return reply(200, {
					ok: true,
					message: "Connected. Four Burners is ready for Siri."
				});
				case "goals": return reply(200, await listGoals(ctx));
				case "people": return reply(200, await listPeople(ctx));
				case "log": return reply(200, await logGoal(ctx));
				case "touch": return reply(200, await logTouch(ctx));
				case "health": return reply(200, await applyHealth(ctx));
				default: return reply(400, {
					ok: false,
					message: `Unknown action "${action.slice(0, 20)}". Use log, touch, health, goals, people or ping.`
				});
			}
		} catch (e) {
			deps.log?.(`request failed: ${e instanceof Error ? e.message : String(e)}`);
			return reply(500, {
				ok: false,
				message: "Four Burners couldn't save that right now. Try again in a minute."
			});
		}
	};
}
//#endregion
//#region src/server/shortcuts/store.ts
var RestError = class extends Error {
	status;
	constructor(status, message) {
		super(message);
		this.status = status;
	}
};
const PAGE = 1e3;
function restShortcutsStore(supabaseUrl, key, fetchFn) {
	const base = supabaseUrl.replace(/\/+$/, "");
	const auth = {
		apikey: key,
		...key.startsWith("eyJ") ? { Authorization: `Bearer ${key}` } : {}
	};
	const q = (params) => new URLSearchParams(params).toString();
	async function call(path, init = {}) {
		const res = await fetchFn(`${base}${path}`, {
			...init,
			headers: {
				...auth,
				...init.headers
			}
		});
		if (!res.ok) throw new RestError(res.status, `${init.method ?? "GET"} ${path.split("?")[0]}: HTTP ${res.status} ${(await res.text().catch(() => "")).slice(0, 200)}`);
		return res;
	}
	const json = async (path, init) => await (await call(path, init)).json();
	async function records(userId, collection, filters = {}) {
		const out = [];
		for (let offset = 0;; offset += PAGE) {
			const page = await json(`/rest/v1/records?${q({
				select: "data",
				user_id: `eq.${userId}`,
				collection: `eq.${collection}`,
				deleted: "is.false",
				...filters,
				order: "id",
				limit: String(PAGE),
				offset: String(offset)
			})}`);
			out.push(...page.map((r) => r.data));
			if (page.length < PAGE) return out;
		}
	}
	return {
		async tokenByHash(hash) {
			const rows = await json(`/rest/v1/shortcut_tokens?${q({
				select: "id,user_id",
				token_hash: `eq.${hash}`
			})}`);
			return rows[0] ? {
				id: rows[0].id,
				userId: rows[0].user_id
			} : null;
		},
		async markTokenUsed(id, at) {
			await call(`/rest/v1/shortcut_tokens?${q({ id: `eq.${id}` })}`, {
				method: "PATCH",
				headers: {
					"Content-Type": "application/json",
					Prefer: "return=minimal"
				},
				body: JSON.stringify({ last_used_at: at })
			});
		},
		async settings(userId) {
			return (await json(`/rest/v1/records?${q({
				select: "data",
				user_id: `eq.${userId}`,
				collection: "eq.kv",
				id: "eq.settings",
				deleted: "is.false"
			})}`))[0]?.data?.value;
		},
		async latestTimeZone(userId) {
			try {
				return (await json(`/rest/v1/push_subscriptions?${q({
					select: "time_zone",
					user_id: `eq.${userId}`,
					order: "last_seen_at.desc",
					limit: "1"
				})}`))[0]?.time_zone ?? null;
			} catch {
				return null;
			}
		},
		async quarter(userId, quarterId) {
			return (await records(userId, "quarters", { id: `eq.${quarterId}` }))[0];
		},
		goals: (userId, quarterId) => records(userId, "goals", { "data->>quarterId": `eq.${quarterId}` }),
		people: (userId) => records(userId, "people"),
		logsForGoal: (userId, goalId) => records(userId, "logs", { "data->>goalId": `eq.${goalId}` }),
		async get(userId, collection, id) {
			return (await json(`/rest/v1/records?${q({
				select: "data,deleted,updated_at",
				user_id: `eq.${userId}`,
				collection: `eq.${collection}`,
				id: `eq.${id}`
			})}`))[0] ?? null;
		},
		async put(userId, collection, record) {
			return await json("/rest/v1/rpc/shortcuts_put_record", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					p_user: userId,
					p_collection: collection,
					p_id: record.id,
					p_data: record,
					p_updated_at: record.updatedAt
				})
			}) === true;
		}
	};
}
//#endregion
//#region src/server/shortcuts/entry.deno.ts
const env = (name) => Deno.env.get(name);
const supabaseUrl = env("SUPABASE_URL");
const serviceKey = serviceKeyFrom(env, "SHORTCUTS_SERVICE_KEY");
Deno.serve(supabaseUrl && serviceKey ? createShortcutsHandler({
	store: restShortcutsStore(supabaseUrl, serviceKey, fetch),
	now: () => new Date(),
	newId: () => crypto.randomUUID(),
	log: (msg) => console.error(msg)
}) : async () => new Response(JSON.stringify({
	ok: false,
	message: "The shortcuts function is missing SUPABASE_URL or its service key."
}), {
	status: 500,
	headers: { "Content-Type": "application/json" }
}));
//#endregion
