// @ts-nocheck
// GENERATED by `npm run build:functions` from src/server/calendar and src/domain. Do not edit by hand.
// The Four Burners calendar Edge Function: reads a calendar feed (ICS) for Travel/Crunch suggestions. Stores nothing.
// Deploy: README.
//#region src/server/env.ts
function serviceKeyFrom(env, override) {
	const explicit = env(override);
	if (explicit) return explicit;
	try {
		const keys = JSON.parse(env("SUPABASE_SECRET_KEYS") ?? "{}");
		const k = keys.default ?? Object.values(keys)[0];
		if (typeof k === "string" && k) return k;
	} catch {}
	return env("SUPABASE_SERVICE_ROLE_KEY") || void 0;
}
//#endregion
//#region src/domain/dates.ts
const DAY_MS = 864e5;
function toUtcMs(d) {
	const [y, m, day] = d.split("-").map(Number);
	return Date.UTC(y, m - 1, day);
}
function fromUtcMs(ms) {
	return new Date(ms).toISOString().slice(0, 10);
}
function addDays(d, n) {
	return fromUtcMs(toUtcMs(d) + n * DAY_MS);
}
function localDateFor(instant, offsetMin, dayBoundaryHour) {
	const shifted = instant.getTime() + offsetMin * 6e4 - dayBoundaryHour * 36e5;
	return fromUtcMs(Math.floor(shifted / DAY_MS) * DAY_MS);
}
new Set("four burners burner coach packet end of family friends health work high steady low suggested actions action type week weekly review quarter crunch me why when pace active trimmed redacted progress consistency streak energy days day wins misses notes note people goals goal draft last prior off track ask load now done yes no travel life theme people setup check in about the and a".split(" "));
//#endregion
//#region src/domain/calendar.ts
function normalizeFeedUrl(input) {
	if (typeof input !== "string") return null;
	const raw = input.trim().replace(/^webcals?:\/\//i, "https://");
	if (raw.length > 2e3) return null;
	let u;
	try {
		u = new URL(raw);
	} catch {
		return null;
	}
	if (u.protocol !== "https:" || !u.hostname || u.username || u.password) return null;
	return u.toString();
}
function isPublicFeedHost(hostname) {
	const h = hostname.toLowerCase().replace(/\.$/, "");
	if (!h.includes(".")) return false;
	if (/^[\d.]+$/.test(h) || h.includes(":") || h.startsWith("[")) return false;
	if (/(^|\.)(localhost|local|internal|intranet|lan|home|corp|localdomain|supabase\.internal)$/.test(h)) return false;
	return /^[a-z0-9.-]+$/.test(h);
}
function isPrivateAddress(ip) {
	const a = ip.trim().toLowerCase().replace(/^\[|\]$/g, "");
	const v4 = /^(\d+)\.(\d+)\.(\d+)\.(\d+)$/.exec(a.replace(/^::ffff:/, ""));
	if (v4) {
		const [x, y] = [Number(v4[1]), Number(v4[2])];
		return x === 0 || x === 10 || x === 127 || x >= 224 || x === 100 && y >= 64 && y <= 127 || x === 169 && y === 254 || x === 172 && y >= 16 && y <= 31 || x === 192 && y === 168 || x === 198 && (y === 18 || y === 19);
	}
	if (!a.includes(":")) return true;
	return a === "::" || a === "::1" || /^f[cd]/.test(a) || /^fe[89ab]/.test(a) || /^ff/.test(a) || a.startsWith("64:ff9b:");
}
function unescapeText(s) {
	return s.replace(/\\([nN,;\\])/g, (_, c) => c === "n" || c === "N" ? " " : c).replace(/\s+/g, " ").trim();
}
function parseLine(line) {
	let inQuote = false;
	let colon = -1;
	for (let i = 0; i < line.length; i++) {
		const c = line[i];
		if (c === "\"") inQuote = !inQuote;
		else if (c === ":" && !inQuote) {
			colon = i;
			break;
		}
	}
	if (colon < 0) return null;
	const [name, ...params] = line.slice(0, colon).split(";");
	const p = {};
	for (const kv of params) {
		const eq = kv.indexOf("=");
		if (eq > 0) p[kv.slice(0, eq).toUpperCase()] = kv.slice(eq + 1).replace(/^"|"$/g, "");
	}
	return {
		name: name.toUpperCase(),
		params: p,
		value: line.slice(colon + 1)
	};
}
function parseWhen(p, offsetMin, dayBoundaryHour) {
	const m = /^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?(Z)?)?$/.exec(p.value.trim());
	if (!m) return null;
	const date = `${m[1]}-${m[2]}-${m[3]}`;
	const ms = Date.UTC(+m[1], +m[2] - 1, +m[3], +(m[4] ?? 0), +(m[5] ?? 0), +(m[6] ?? 0));
	if (!Number.isFinite(ms)) return null;
	if (!m[4] || p.params.VALUE === "DATE") return {
		date,
		allDay: true,
		midnight: false,
		ms
	};
	const midnight = m[4] === "00" && m[5] === "00" && (m[6] ?? "00") === "00";
	if (m[7] === "Z") {
		const at = new Date(ms);
		const localMin = ((at.getUTCHours() * 60 + at.getUTCMinutes() + offsetMin) % 1440 + 1440) % 1440;
		return {
			date: localDateFor(at, offsetMin, dayBoundaryHour),
			allDay: false,
			midnight: localMin === 0,
			ms
		};
	}
	return {
		date,
		allDay: false,
		midnight,
		ms
	};
}
function durationDays(v) {
	const m = /^P(?:(\d+)W)?(?:(\d+)D)?(?:T(?:(\d+)H)?)?/.exec(v.trim());
	if (!m) return 0;
	return Number(m[1] ?? 0) * 7 + Number(m[2] ?? 0) + Math.floor(Number(m[3] ?? 0) / 24);
}
const MAX_EVENTS = 2e4;
function parseIcs(text, window, offsetMin = 0, dayBoundaryHour = 0) {
	const lines = text.replace(/\r\n?/g, "\n").replace(/\n[ \t]/g, "").split("\n");
	const out = {
		events: [],
		skippedRecurring: 0
	};
	let ev = null;
	let depth = 0;
	let seen = 0;
	for (const line of lines) {
		if (!line) continue;
		const up = line.toUpperCase();
		if (up === "BEGIN:VEVENT") {
			ev = {};
			depth = 0;
			continue;
		}
		if (ev && up.startsWith("BEGIN:")) {
			depth++;
			continue;
		}
		if (ev && up.startsWith("END:") && up !== "END:VEVENT") {
			depth = Math.max(0, depth - 1);
			continue;
		}
		if (up === "END:VEVENT") {
			if (ev && ++seen <= MAX_EVENTS) {
				const e = toEvent(ev, offsetMin, dayBoundaryHour);
				if (e === "recurring") out.skippedRecurring++;
				else if (e && e.end >= window.from && e.start <= window.to) out.events.push(e);
			}
			ev = null;
			continue;
		}
		const p = parseLine(line);
		if (!p) continue;
		if (ev) {
			if (depth === 0 && !(p.name in ev)) ev[p.name] = p;
		} else if (p.name === "X-WR-CALNAME" && !out.name) out.name = unescapeText(p.value).slice(0, 80);
	}
	out.events.sort((a, b) => a.start < b.start ? -1 : a.start > b.start ? 1 : 0);
	return out;
}
function toEvent(ev, offsetMin, dayBoundaryHour) {
	if (ev.STATUS?.value.trim().toUpperCase() === "CANCELLED") return null;
	if (ev.RRULE || ev.RDATE) return "recurring";
	const start = ev.DTSTART && parseWhen(ev.DTSTART, offsetMin, dayBoundaryHour);
	if (!start) return null;
	let end = start.date;
	let hours;
	const dtend = ev.DTEND && parseWhen(ev.DTEND, offsetMin, dayBoundaryHour);
	if (dtend) {
		end = dtend.allDay || dtend.midnight ? addDays(dtend.date, -1) : dtend.date;
		if (!start.allDay) hours = Math.max(0, (dtend.ms - start.ms) / 36e5);
	} else if (ev.DURATION) {
		const days = durationDays(ev.DURATION.value);
		end = start.allDay ? addDays(start.date, Math.max(1, days) - 1) : addDays(start.date, days);
		if (!start.allDay) hours = durationHours(ev.DURATION.value);
	}
	if (end < start.date) end = start.date;
	const outlookAllDay = ev["X-MICROSOFT-CDO-ALLDAYEVENT"]?.value.trim().toUpperCase() === "TRUE";
	const allDay = start.allDay || outlookAllDay || start.midnight && !!dtend?.midnight && (hours ?? 0) >= 24;
	return {
		summary: unescapeText(ev.SUMMARY?.value ?? "").slice(0, 120),
		...ev.LOCATION?.value ? { location: unescapeText(ev.LOCATION.value).slice(0, 120) } : {},
		start: start.date,
		end,
		allDay,
		free: ev.TRANSP?.value.trim().toUpperCase() === "TRANSPARENT",
		...!allDay && hours !== void 0 ? { hours: Math.round(hours * 10) / 10 } : {}
	};
}
function durationHours(v) {
	const m = /^P(?:(\d+)W)?(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?)?/.exec(v.trim());
	if (!m) return 0;
	return Number(m[1] ?? 0) * 168 + Number(m[2] ?? 0) * 24 + Number(m[3] ?? 0) + Number(m[4] ?? 0) / 60;
}
//#endregion
//#region src/server/calendar/handler.ts
const CORS = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
	"Access-Control-Allow-Methods": "POST, OPTIONS"
};
const FEED_MESSAGES = {
	bad_url: "That doesn't look like a calendar link. Use the https or webcal address from your calendar's sharing settings.",
	refused: "The calendar refused that link. It may have been reset: copy a fresh one.",
	not_found: "No calendar at that link. It may have been reset or unshared: copy a fresh one.",
	not_calendar: "That link didn't return a calendar file (ICS).",
	too_large: "That calendar is too large to read (over 5 MB).",
	unavailable: "Couldn't reach the calendar right now. It will try again later."
};
const MAX_BYTES = 5242880;
const MAX_REDIRECTS = 3;
const TIMEOUT_MS = 15e3;
const WINDOW = {
	back: 7,
	ahead: 60
};
function reply(status, body) {
	return new Response(JSON.stringify(body), {
		status,
		headers: {
			...CORS,
			"Content-Type": "application/json"
		}
	});
}
const fail = (code) => reply(200, {
	ok: false,
	code,
	message: FEED_MESSAGES[code]
});
async function readCapped(res) {
	if (Number(res.headers.get("content-length") ?? 0) > MAX_BYTES) return "too_large";
	if (!res.body) return await res.text();
	const reader = res.body.getReader();
	const chunks = [];
	let total = 0;
	for (;;) {
		const { done, value } = await reader.read();
		if (done) break;
		total += value.length;
		if (total > MAX_BYTES) {
			await reader.cancel().catch(() => void 0);
			return "too_large";
		}
		chunks.push(value);
	}
	const all = new Uint8Array(total);
	let o = 0;
	for (const c of chunks) {
		all.set(c, o);
		o += c.length;
	}
	return new TextDecoder().decode(all);
}
async function safeHost(u, resolve) {
	if (u.protocol !== "https:" || u.port && u.port !== "443" || !isPublicFeedHost(u.hostname)) return false;
	if (!resolve) return true;
	const addrs = await resolve(u.hostname).catch(() => null);
	return addrs === null || !addrs.some(isPrivateAddress);
}
async function fetchFeed(url, fetchFn, resolve) {
	let next = url;
	for (let hop = 0; hop <= MAX_REDIRECTS; hop++) {
		let u;
		try {
			u = new URL(next);
		} catch {
			return {
				ok: false,
				code: "bad_url"
			};
		}
		if (!await safeHost(u, resolve)) return {
			ok: false,
			code: "bad_url"
		};
		let res;
		try {
			res = await fetchFn(u.toString(), {
				redirect: "manual",
				headers: {
					Accept: "text/calendar, text/plain;q=0.9, */*;q=0.5",
					"User-Agent": "FourBurners/1 (calendar feed)"
				},
				signal: AbortSignal.timeout(TIMEOUT_MS)
			});
		} catch {
			return {
				ok: false,
				code: "unavailable"
			};
		}
		if (res.status >= 300 && res.status < 400) {
			const loc = res.headers.get("location");
			if (!loc) return {
				ok: false,
				code: "unavailable"
			};
			let target = null;
			try {
				target = normalizeFeedUrl(new URL(loc, u).toString());
			} catch {}
			if (!target) return {
				ok: false,
				code: "bad_url"
			};
			next = target;
			continue;
		}
		if (res.status === 401 || res.status === 403) return {
			ok: false,
			code: "refused"
		};
		if (res.status === 404 || res.status === 410) return {
			ok: false,
			code: "not_found"
		};
		if (!res.ok) return {
			ok: false,
			code: "unavailable"
		};
		let text;
		try {
			text = await readCapped(res);
		} catch {
			return {
				ok: false,
				code: "unavailable"
			};
		}
		if (text === "too_large") return {
			ok: false,
			code: "too_large"
		};
		if (!/BEGIN:VCALENDAR/i.test(text.slice(0, 4096))) return {
			ok: false,
			code: "not_calendar"
		};
		return {
			ok: true,
			text
		};
	}
	return {
		ok: false,
		code: "unavailable"
	};
}
function createCalendarHandler(deps) {
	return async (req) => {
		if (req.method === "OPTIONS") return new Response(null, {
			status: 204,
			headers: CORS
		});
		if (req.method !== "POST") return reply(405, {
			ok: false,
			message: "POST only"
		});
		try {
			const token = /^Bearer\s+(.+)$/i.exec(req.headers.get("authorization") ?? "")?.[1];
			if (!(token ? await deps.userFromToken(token) : null)) return reply(401, {
				ok: false,
				message: "Sign in required"
			});
			const body = await req.json().catch(() => ({}));
			const url = normalizeFeedUrl(body.url);
			if (!url) return fail("bad_url");
			const now = deps.now();
			const offsetMin = typeof body.offsetMin === "number" && Math.abs(body.offsetMin) <= 840 ? Math.round(body.offsetMin) : 0;
			const today = typeof body.today === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.today) ? body.today : now.toISOString().slice(0, 10);
			const boundary = typeof body.dayBoundaryHour === "number" && Number.isInteger(body.dayBoundaryHour) && body.dayBoundaryHour >= 0 && body.dayBoundaryHour <= 23 ? body.dayBoundaryHour : 0;
			const feed = await fetchFeed(url, deps.fetch, deps.resolve);
			if (!feed.ok) return fail(feed.code);
			return reply(200, {
				ok: true,
				...parseIcs(feed.text, {
					from: addDays(today, -WINDOW.back),
					to: addDays(today, WINDOW.ahead)
				}, offsetMin, boundary)
			});
		} catch (e) {
			deps.log?.(`calendar request failed: ${e instanceof Error ? e.name : "error"}`);
			return reply(500, {
				ok: false,
				message: "Server error"
			});
		}
	};
}
//#endregion
//#region src/server/calendar/entry.deno.ts
const env = (name) => Deno.env.get(name);
const supabaseUrl = env("SUPABASE_URL")?.replace(/\/+$/, "");
const apiKey = serviceKeyFrom(env, "CALENDAR_SERVICE_KEY") ?? env("SUPABASE_ANON_KEY");
Deno.serve(supabaseUrl && apiKey ? createCalendarHandler({
	async userFromToken(token) {
		const res = await fetch(`${supabaseUrl}/auth/v1/user`, { headers: {
			apikey: apiKey,
			Authorization: `Bearer ${token}`
		} });
		if (!res.ok) return null;
		const user = await res.json().catch(() => null);
		return typeof user?.id === "string" ? user.id : null;
	},
	fetch,
	async resolve(host) {
		if (typeof Deno.resolveDns !== "function") return null;
		const [a, aaaa] = await Promise.allSettled([Deno.resolveDns(host, "A"), Deno.resolveDns(host, "AAAA")]);
		if (a.status === "rejected" && aaaa.status === "rejected") return null;
		return [...a.status === "fulfilled" ? a.value : [], ...aaaa.status === "fulfilled" ? aaaa.value : []];
	},
	now: () => new Date(),
	log: (msg) => console.error(msg)
}) : async () => new Response(JSON.stringify({
	ok: false,
	message: "The calendar function is missing SUPABASE_URL or its key."
}), {
	status: 500,
	headers: { "Content-Type": "application/json" }
}));
//#endregion
