// @ts-nocheck
// GENERATED by `npm run build:functions` from src/server/notify and src/domain. Do not edit by hand.
// The Four Burners notify Edge Function: sends daily, weekly and smart-nudge Web Push notifications.
// Deploy: README > Notifications.
//#region src/domain/types.ts
const BURNERS = [
	"family",
	"friends",
	"health",
	"work"
];
const BURNER_LABELS = {
	family: "Family",
	friends: "Friends",
	health: "Health",
	work: "Work"
};
const DEFAULT_NOTIFY_PREFS = {
	daily: {
		on: true,
		time: "20:00"
	},
	weekly: {
		on: true,
		time: "17:00"
	},
	nudges: true,
	quiet: {
		on: true,
		start: "22:00",
		end: "07:00"
	}
};
const DEFAULT_SETTINGS = {
	dayBoundaryHour: 3,
	graceDaysPerWeek: 1,
	soundEffects: true,
	haptics: true,
	reviewDay: 6,
	sensitiveTerms: [],
	notify: DEFAULT_NOTIFY_PREFS
};
//#endregion
//#region src/domain/config.ts
const INTENT_WEIGHTS = {
	high: 3,
	steady: 2,
	low: 1
};
const INTENT_EXPECTATION = {
	high: 1,
	steady: .85,
	low: .6
};
const PACE_THRESHOLDS = {
	onTrack: .9,
	behind: .6
};
const RECENT_ACTIVE_DAYS = {
	high: 4,
	steady: 2.5,
	low: 1
};
const DIM_GRACE_DAYS = {
	high: 3,
	steady: 5,
	low: 10
};
const DIM_FLOOR = .4;
const PILOT_BRIGHTNESS = .75;
const PILOT_HEAT = .15;
const CRUNCH_EXPECTATION = .25;
const NUDGE_WINDOW = {
	start: "11:00",
	end: "19:00"
};
const NUDGE_PACE = {
	high: .75,
	steady: .6,
	low: .35
};
const NUDGE_QUIET_DAYS = {
	high: 2,
	steady: 4,
	low: 14
};
const NUDGE_COOLDOWN_DAYS = {
	high: 3,
	steady: 5,
	low: 14
};
const PERSON_NUDGE_RATIO = {
	high: 1.35,
	steady: 1.35,
	low: 2
};
//#endregion
//#region src/domain/dates.ts
const DAY_MS = 864e5;
function toUtcMs(d) {
	const [y, m, day] = d.split("-").map(Number);
	return Date.UTC(y, m - 1, day);
}
function fromUtcMs(ms) {
	return new Date(ms).toISOString().slice(0, 10);
}
function addDays(d, n) {
	return fromUtcMs(toUtcMs(d) + n * DAY_MS);
}
function diffDays(a, b) {
	return Math.round((toUtcMs(b) - toUtcMs(a)) / DAY_MS);
}
function maxDate(a, b) {
	return a > b ? a : b;
}
function weekday(d) {
	return (new Date(toUtcMs(d)).getUTCDay() + 6) % 7;
}
function startOfWeek(d) {
	return addDays(d, -weekday(d));
}
function dateRange(a, b) {
	const out = [];
	for (let d = a; d <= b; d = addDays(d, 1)) out.push(d);
	return out;
}
function localDateFor(instant, offsetMin, dayBoundaryHour) {
	const shifted = instant.getTime() + offsetMin * 6e4 - dayBoundaryHour * 36e5;
	return fromUtcMs(Math.floor(shifted / DAY_MS) * DAY_MS);
}
function quarterOf(d) {
	return quarterSpan(`${Number(d.slice(0, 4))}-Q${Math.floor((Number(d.slice(5, 7)) - 1) / 3) + 1}`);
}
function quarterSpan(id) {
	const [ys, qs] = id.split("-Q");
	const y = Number(ys);
	const q = Number(qs);
	const startMonth = (q - 1) * 3 + 1;
	return {
		id,
		start: `${y}-${String(startMonth).padStart(2, "0")}-01`,
		end: addDays(q === 4 ? `${y + 1}-01-01` : `${y}-${String(startMonth + 3).padStart(2, "0")}-01`, -1)
	};
}
//#endregion
//#region src/domain/goals.ts
const MONTH_DAYS = 365.25 / 12;
function windowDays(goal) {
	return Math.max(1, diffDays(goal.startDate, goal.deadline) + 1);
}
function requiredFor(goal) {
	switch (goal.type) {
		case "number": return Math.max(0, goal.target ?? 0);
		case "habit": {
			const perPeriod = Math.max(0, goal.target ?? 0);
			const periodDays = goal.habitPeriod === "month" ? MONTH_DAYS : 7;
			return Math.max(perPeriod > 0 ? 1 : 0, Math.round(perPeriod * windowDays(goal) / periodDays));
		}
		case "yesno": return 1;
		case "milestone": return goal.milestones?.length ?? 0;
	}
}
function actualFor(goal, logs) {
	const mine = logs.filter((l) => l.goalId === goal.id && !l.deleted);
	switch (goal.type) {
		case "number":
		case "habit": return mine.reduce((s, l) => s + l.value, 0);
		case "yesno": return mine.some((l) => l.value > 0) ? 1 : 0;
		case "milestone": {
			const done = new Set(mine.map((l) => l.milestoneId).filter(Boolean));
			return goal.milestones?.filter((m) => done.has(m.id)).length ?? 0;
		}
	}
}
function elapsedFraction(goal, today, crunchDates) {
	if (today < goal.startDate) return 0;
	const total = windowDays(goal);
	if (today > goal.deadline) return weightedDays(goal.startDate, goal.deadline, crunchDates) / total;
	const beforeToday = today > goal.startDate ? weightedDays(goal.startDate, addDays(today, -1), crunchDates) : 0;
	const todayWeight = crunchDates?.has(today) ? CRUNCH_EXPECTATION : 1;
	return Math.min(1, (beforeToday + .5 * todayWeight) / total);
}
function weightedDays(a, b, crunch) {
	if (b < a) return 0;
	if (!crunch || crunch.size === 0) return diffDays(a, b) + 1;
	let sum = 0;
	for (const d of dateRange(a, b)) sum += crunch.has(d) ? CRUNCH_EXPECTATION : 1;
	return sum;
}
function shapeExpectation(type, elapsed) {
	return type === "yesno" ? elapsed * elapsed : elapsed;
}
function goalProgress(goal, logs, today, ctx) {
	const required = requiredFor(goal);
	const actual = actualFor(goal, logs);
	const fraction = required > 0 ? Math.min(1, actual / required) : 0;
	const complete = required > 0 && actual >= required;
	const elapsed = elapsedFraction(goal, today, ctx.crunchDates);
	const expected = shapeExpectation(goal.type, elapsed) * INTENT_EXPECTATION[ctx.intent];
	let pace;
	if (complete) pace = 1;
	else if (expected < .02 || diffDays(goal.startDate, today) < 2) pace = 1;
	else pace = Math.min(1, fraction / expected);
	const status = complete ? "done" : pace >= PACE_THRESHOLDS.onTrack ? "on_track" : pace >= PACE_THRESHOLDS.behind ? "behind" : "slipping";
	return {
		actual,
		required,
		fraction,
		expected,
		pace,
		status,
		complete
	};
}
//#endregion
//#region src/domain/streaks.ts
function dailyStreak({ activeDates, today, graceDaysPerWeek, pausedDates }) {
	if (activeDates.size === 0) return {
		current: 0,
		longest: 0,
		graceUsedThisWeek: 0
	};
	const first = [...activeDates].sort()[0];
	if (first > today) return {
		current: 0,
		longest: 0,
		graceUsedThisWeek: 0
	};
	const graceUsed = new Map();
	let run = 0;
	let longest = 0;
	for (const d of dateRange(first, today)) {
		if (activeDates.has(d)) run++;
		else if (pausedDates?.has(d) || d === today) {} else if (run > 0) {
			const wk = startOfWeek(d);
			const used = graceUsed.get(wk) ?? 0;
			if (used < graceDaysPerWeek) graceUsed.set(wk, used + 1);
			else run = 0;
		}
		if (run === 0) graceUsed.clear();
		longest = Math.max(longest, run);
	}
	return {
		current: run,
		longest,
		graceUsedThisWeek: run > 0 ? graceUsed.get(startOfWeek(today)) ?? 0 : 0
	};
}
function timeZoneExcusedDates(stamps, dayBoundaryHour) {
	const out = new Set();
	const sorted = [...stamps].sort((a, b) => a.at < b.at ? -1 : a.at > b.at ? 1 : 0);
	for (let i = 1; i < sorted.length; i++) {
		const a = sorted[i - 1];
		const b = sorted[i];
		if (a.offsetMin === b.offsetMin) continue;
		if (diffDays(a.localDate, b.localDate) < 2) continue;
		const ta = new Date(a.at);
		const tb = new Date(b.at);
		if ([a.offsetMin, b.offsetMin].some((o) => diffDays(localDateFor(ta, o, dayBoundaryHour), localDateFor(tb, o, dayBoundaryHour)) <= 1)) for (let d = addDays(a.localDate, 1); d < b.localDate; d = addDays(d, 1)) out.add(d);
	}
	return out;
}
function consistencyScore(input) {
	const { activeDates, today, graceDaysPerWeek, pausedDates, since } = input;
	const start = maxDate(since, addDays(today, -27));
	if (start > today) return 0;
	const byWeek = new Map();
	let counted = 0;
	for (const d of dateRange(start, today)) {
		if (pausedDates?.has(d)) continue;
		const isActive = activeDates.has(d);
		if (d === today && !isActive) continue;
		counted++;
		const wk = startOfWeek(d);
		const w = byWeek.get(wk) ?? {
			active: 0,
			missed: 0
		};
		if (isActive) w.active++;
		else w.missed++;
		byWeek.set(wk, w);
	}
	if (counted === 0) return activeDates.has(today) ? 100 : 0;
	let covered = 0;
	for (const w of byWeek.values()) covered += w.active + (w.active > 0 ? Math.min(w.missed, graceDaysPerWeek) : 0);
	const coverage = Math.min(1, covered / counted);
	const streak = dailyStreak(input).current;
	const bonus = Math.min(1, streak / 14);
	return Math.round((coverage * .85 + bonus * .15) * 100);
}
//#endregion
//#region src/domain/scoring.ts
function crunchDateSet(periods, today) {
	const out = new Set();
	for (const p of periods) {
		if (p.deleted) continue;
		const end = p.end && p.end < today ? p.end : today;
		if (p.start > end) continue;
		for (const d of dateRange(p.start, end)) out.add(d);
	}
	return out;
}
function activeCrunch(periods, today) {
	return periods.find((p) => !p.deleted && p.start <= today && (!p.end || p.end >= today));
}
function upTo(xs, asOf) {
	return xs.filter((x) => !x.deleted && x.localDate <= asOf);
}
function checkInStamps(input, asOf = "9999-12-31") {
	const actionStamps = (input.actions ?? []).filter((a) => !a.deleted && a.done).map((a) => a.done);
	return [
		...upTo(input.logs, asOf),
		...upTo(input.energy, asOf),
		...upTo(input.touchpoints, asOf),
		...actionStamps.filter((s) => s.localDate <= asOf)
	];
}
function burnerActivity(input, asOf) {
	const out = {
		family: new Set(),
		friends: new Set(),
		health: new Set(),
		work: new Set()
	};
	const goalBurner = new Map(input.goals.filter((g) => !g.deleted).map((g) => [g.id, g.burner]));
	const personBurner = new Map(input.people.filter((p) => !p.deleted).map((p) => [p.id, p.burner]));
	for (const l of upTo(input.logs, asOf)) {
		const b = goalBurner.get(l.goalId);
		if (b) out[b].add(l.localDate);
	}
	for (const t of upTo(input.touchpoints, asOf)) {
		const b = personBurner.get(t.personId);
		if (b) out[b].add(t.localDate);
	}
	for (const a of input.actions ?? []) if (!a.deleted && a.done && a.burner && a.done.localDate <= asOf) out[a.burner].add(a.done.localDate);
	return out;
}
function computeDashboard(input) {
	const { quarter, goals, settings, today } = input;
	const crunch = crunchDateSet(input.crunch, today);
	const stamps = checkInStamps(input, today);
	const activeDates = new Set(stamps.map((s) => s.localDate));
	const paused = new Set([...crunch, ...timeZoneExcusedDates(stamps, settings.dayBoundaryHour)]);
	const liveGoals = goals.filter((g) => !g.deleted && g.quarterId === quarter.id);
	const liveLogs = upTo(input.logs, today);
	const activityByBurner = burnerActivity({
		...input,
		goals: liveGoals
	}, today);
	const last7 = dateRange(addDays(today, -6), today);
	const nonCrunchLast7 = last7.filter((d) => !crunch.has(d)).length;
	const burners = {};
	let weighted = 0;
	let weights = 0;
	for (const b of BURNERS) {
		const intent = quarter.intents[b];
		const bGoals = liveGoals.filter((g) => g.burner === b).sort((x, y) => x.order - y.order).map((goal) => ({
			goal,
			progress: goalProgress(goal, liveLogs, today, {
				intent,
				crunchDates: crunch
			})
		}));
		const pace = bGoals.length ? bGoals.reduce((s, g) => s + g.progress.pace, 0) / bGoals.length : null;
		if (pace !== null) {
			weighted += INTENT_WEIGHTS[intent] * pace;
			weights += INTENT_WEIGHTS[intent];
		}
		const act = activityByBurner[b];
		const activeDaysLast7 = last7.filter((d) => act.has(d)).length;
		const needed = RECENT_ACTIVE_DAYS[intent] * (nonCrunchLast7 / 7);
		const recent = needed < .5 ? 1 : Math.min(1, activeDaysLast7 / needed);
		const heat = Math.max(PILOT_HEAT, pace === null ? recent : .6 * pace + .4 * recent);
		const sorted = [...act].sort();
		const lastActive = sorted[sorted.length - 1];
		const firstGoalStart = bGoals.map((g) => g.goal.startDate).sort()[0];
		const quietFrom = lastActive ?? firstGoalStart;
		let brightness;
		if (!quietFrom) brightness = PILOT_BRIGHTNESS;
		else {
			const quietDays = quietFrom >= today ? 0 : dateRange(addDays(quietFrom, 1), today).filter((d) => !crunch.has(d)).length;
			const over = Math.max(0, quietDays - DIM_GRACE_DAYS[intent]);
			brightness = Math.max(DIM_FLOOR, 1 - over / 21 * .6);
		}
		const status = pace === null ? act.size ? "on_track" : "idle" : pace >= .9 ? "on_track" : pace >= .6 ? "behind" : "slipping";
		burners[b] = {
			burner: b,
			intent,
			goals: bGoals,
			pace,
			heat,
			brightness,
			status,
			lastActive,
			activeDaysLast7
		};
	}
	const since = [...activeDates].sort()[0] ?? today;
	const streakInput = {
		activeDates,
		today,
		graceDaysPerWeek: settings.graceDaysPerWeek,
		pausedDates: paused
	};
	return {
		progressScore: weights ? Math.round(weighted / weights * 100) : 0,
		consistencyScore: consistencyScore({
			...streakInput,
			since
		}),
		streak: dailyStreak(streakInput),
		burners,
		inCrunchToday: crunch.has(today)
	};
}
//#endregion
//#region src/domain/people.ts
const CADENCE_THRESHOLDS = {
	approaching: .7,
	due: 1,
	overdue: 1.35
};
const CADENCE_OPTIONS = [
	{
		days: 3,
		label: "Every few days"
	},
	{
		days: 7,
		label: "Every week"
	},
	{
		days: 14,
		label: "Every 2 weeks"
	},
	{
		days: 30,
		label: "Monthly"
	},
	{
		days: 60,
		label: "Every 2 months"
	},
	{
		days: 90,
		label: "Quarterly"
	}
];
function cadenceLabel(days) {
	return CADENCE_OPTIONS.find((o) => o.days === days)?.label ?? `Every ${days} days`;
}
function personStatus(person, touchpoints, today) {
	let lastDate;
	for (const t of touchpoints) {
		if (t.deleted || t.personId !== person.id || t.localDate > today) continue;
		if (!lastDate || t.localDate > lastDate) lastDate = t.localDate;
	}
	if (!lastDate) return {
		person,
		daysSince: null,
		daysUntilDue: null,
		ratio: null,
		state: "never"
	};
	const daysSince = diffDays(lastDate, today);
	const ratio = daysSince / Math.max(1, person.cadenceDays);
	const state = ratio < CADENCE_THRESHOLDS.approaching ? "fresh" : ratio < CADENCE_THRESHOLDS.due ? "approaching" : ratio < CADENCE_THRESHOLDS.overdue ? "due" : "overdue";
	return {
		person,
		lastDate,
		daysSince,
		daysUntilDue: person.cadenceDays - daysSince,
		ratio,
		state
	};
}
//#endregion
//#region src/domain/reviews.ts
function dueReviewWeek(today, reviewDay) {
	const thisWeek = startOfWeek(today);
	for (const w of [thisWeek, addDays(thisWeek, -7)]) {
		const dueStart = addDays(w, reviewDay);
		if (today >= dueStart && today <= addDays(dueStart, 3)) return w;
	}
	return null;
}
//#endregion
//#region src/domain/coach/redact.ts
const REDACTED = "[redacted]";
const EMBEDDED_MIN = 5;
function escapeRegex(s) {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function cleanTerms(terms) {
	const seen = new Set();
	const out = [];
	for (const raw of terms) {
		const t = raw.replace(/\s+/g, " ").trim();
		if (t.length < 2) continue;
		const k = t.toLocaleLowerCase();
		if (seen.has(k)) continue;
		seen.add(k);
		out.push(t);
	}
	return out;
}
function termPattern(term) {
	const body = term.split(" ").map((p) => escapeRegex(p).replace(/'|’/g, "['’]").replace(/^&$/, "(?:&|and)").replace(/^and$/i, "(?:&|and)")).join("[\\s\\-_.]*");
	return term.replace(/\s/g, "").length >= EMBEDDED_MIN ? body : `(?<![\\p{L}\\p{N}])${body}(?:['’]s|s|es)?(?![\\p{L}\\p{N}])`;
}
function buildRegex(terms) {
	const list = cleanTerms(terms).sort((a, b) => b.length - a.length);
	if (!list.length) return null;
	return new RegExp(list.map(termPattern).join("|"), "giu");
}
function redact(text, terms) {
	const re = buildRegex(terms);
	if (!re) return text;
	return text.normalize("NFKC").replace(re, REDACTED);
}
new Set("four burners burner coach packet end of family friends health work high steady low suggested actions action type week weekly review quarter crunch me why when pace active trimmed redacted progress consistency streak energy days day wins misses notes note people goals goal draft last prior off track ask load now done yes no travel life theme people setup check in about the and a".split(" "));
//#endregion
//#region src/domain/notify.ts
const TIME_RE = /^([01]\d|2[0-3]):([0-5]\d)$/;
function parseTime(s) {
	const m = typeof s === "string" ? TIME_RE.exec(s) : null;
	return m ? Number(m[1]) * 60 + Number(m[2]) : null;
}
const bool = (v, d) => typeof v === "boolean" ? v : d;
const time = (v, d) => parseTime(v) === null ? d : v;
function reminder(v, d) {
	const r = v && typeof v === "object" ? v : {};
	return {
		on: bool(r.on, d.on),
		time: time(r.time, d.time)
	};
}
function notifyPrefsOf(settings) {
	const n = settings?.notify ?? {};
	const d = DEFAULT_NOTIFY_PREFS;
	const q = n.quiet && typeof n.quiet === "object" ? n.quiet : {};
	return {
		daily: reminder(n.daily, d.daily),
		weekly: reminder(n.weekly, d.weekly),
		nudges: bool(n.nudges, d.nudges),
		quiet: {
			on: bool(q.on, d.quiet.on),
			start: time(q.start, d.quiet.start),
			end: time(q.end, d.quiet.end)
		}
	};
}
function settingsOf(value) {
	const v = value && typeof value === "object" ? value : {};
	const d = DEFAULT_SETTINGS;
	const int = (x, lo, hi, def) => typeof x === "number" && Number.isInteger(x) && x >= lo && x <= hi ? x : def;
	return {
		...d,
		dayBoundaryHour: int(v.dayBoundaryHour, 0, 23, d.dayBoundaryHour),
		graceDaysPerWeek: int(v.graceDaysPerWeek, 0, 7, d.graceDaysPerWeek),
		reviewDay: int(v.reviewDay, 0, 6, d.reviewDay),
		sensitiveTerms: Array.isArray(v.sensitiveTerms) ? v.sensitiveTerms.filter((t) => typeof t === "string") : [],
		notify: notifyPrefsOf(v)
	};
}
function isValidTimeZone(tz) {
	if (typeof tz !== "string" || !tz || tz.length > 64) return false;
	try {
		new Intl.DateTimeFormat("en-US", { timeZone: tz });
		return true;
	} catch {
		return false;
	}
}
function zoneOffsetMin(now, timeZone) {
	if (!isValidTimeZone(timeZone)) return 0;
	const parts = new Intl.DateTimeFormat("en-US", {
		timeZone,
		hourCycle: "h23",
		year: "numeric",
		month: "numeric",
		day: "numeric",
		hour: "numeric",
		minute: "numeric",
		second: "numeric"
	}).formatToParts(now);
	const get = (t) => Number(parts.find((p) => p.type === t)?.value ?? 0);
	const asUtc = Date.UTC(get("year"), get("month") - 1, get("day"), get("hour") % 24, get("minute"), get("second"));
	return Math.round((asUtc - Math.floor(now.getTime() / 1e3) * 1e3) / 6e4);
}
function clockIn(now, timeZone, dayBoundaryHour) {
	const offsetMin = zoneOffsetMin(now, timeZone);
	const wall = Math.floor((now.getTime() / 6e4 + offsetMin) % 1440);
	return {
		localDate: localDateFor(now, offsetMin, dayBoundaryHour),
		minutes: (wall + 1440) % 1440,
		offsetMin
	};
}
function livedMinutes(wallMin, dayBoundaryHour) {
	return ((wallMin - dayBoundaryHour * 60) % 1440 + 1440) % 1440;
}
function inQuietHours(wallMin, quiet) {
	if (!quiet.on) return false;
	const s = parseTime(quiet.start);
	const e = parseTime(quiet.end);
	if (s === null || e === null || s === e) return false;
	return s < e ? wallMin >= s && wallMin < e : wallMin >= s || wallMin < e;
}
function reminderDue(clock, at, dayBoundaryHour) {
	const target = parseTime(at);
	if (target === null) return false;
	const late = livedMinutes(clock.minutes, dayBoundaryHour) - livedMinutes(target, dayBoundaryHour);
	return late >= 0 && late < 180;
}
function dueNow(now, timeZone, settings, state) {
	const prefs = notifyPrefsOf(settings);
	const b = settings.dayBoundaryHour;
	const clock = clockIn(now, timeZone, b);
	const quiet = inQuietHours(clock.minutes, prefs.quiet);
	const none = {
		clock,
		quiet,
		daily: false,
		weekly: null,
		nudge: false
	};
	if (quiet) return none;
	const daily = prefs.daily.on && state.dailyDate !== clock.localDate && reminderDue(clock, prefs.daily.time, b);
	let weekly = null;
	if (prefs.weekly.on && weekday(clock.localDate) === settings.reviewDay && reminderDue(clock, prefs.weekly.time, b)) {
		const week = dueReviewWeek(clock.localDate, settings.reviewDay);
		if (week && state.weeklyWeek !== week) weekly = week;
	}
	const lived = livedMinutes(clock.minutes, b);
	const nudge = prefs.nudges && state.nudgeDate !== clock.localDate && lived >= livedMinutes(parseTime(NUDGE_WINDOW.start), b) && lived < livedMinutes(parseTime(NUDGE_WINDOW.end), b);
	return {
		clock,
		quiet,
		daily,
		weekly,
		nudge
	};
}
function clip(s, max) {
	const t = s.replace(/\s+/g, " ").trim();
	return t.length <= max ? t : `${t.slice(0, max - 1).trimEnd()}…`;
}
function dashboardFor(data, settings, today) {
	if (!data.quarter) return null;
	const span = quarterOf(today);
	return computeDashboard({
		quarter: data.quarter,
		quarterStart: span.start,
		goals: data.goals.filter((g) => !g.deleted && g.quarterId === data.quarter.id),
		logs: data.logs,
		energy: data.energy,
		people: data.people,
		touchpoints: data.touchpoints,
		crunch: data.crunch,
		actions: data.actions,
		settings,
		today
	});
}
function composeDaily(data, settings, today) {
	if (activeCrunch(data.crunch, today)) return null;
	if (checkInStamps(data, today).some((s) => s.localDate === today)) return null;
	const streak = dashboardFor(data, settings, today)?.streak.current ?? 0;
	return {
		kind: "daily",
		title: "Time to check in",
		body: streak >= 2 ? `Keep your ${streak} day streak going. Two taps is enough.` : "Two taps keeps your burners lit.",
		url: "/#/",
		tag: "daily"
	};
}
function composeWeekly(data, week) {
	if (data.reviews.some((r) => !r.deleted && r.weekStart === week && r.completedAt)) return null;
	return {
		kind: "weekly",
		title: "Weekly review",
		body: "Look back on your week and pick next week's actions. About ten minutes.",
		url: "/#/review",
		tag: "weekly"
	};
}
function cooledDown(nudged, subject, today, days) {
	const last = nudged?.[subject];
	return !last || diffDays(last, today) >= days;
}
function pickNudge(data, settings, today, nudged = {}) {
	if (activeCrunch(data.crunch, today)) return null;
	const terms = settings.sensitiveTerms;
	const safe = (s, max) => clip(redact(s, terms), max);
	const intentOf = (b) => data.quarter?.intents[b] ?? "steady";
	const candidates = [];
	const dash = dashboardFor(data, settings, today);
	if (dash) for (const s of Object.values(dash.burners)) {
		const intent = s.intent;
		if (s.pace === null || s.pace >= NUDGE_PACE[intent]) continue;
		if ((s.lastActive ? diffDays(s.lastActive, today) : Infinity) < NUDGE_QUIET_DAYS[intent]) continue;
		const subject = `burner:${s.burner}`;
		if (!cooledDown(nudged, subject, today, NUDGE_COOLDOWN_DAYS[intent])) continue;
		const worst = s.goals.filter((g) => !g.progress.complete).sort((a, b) => a.progress.pace - b.progress.pace)[0];
		if (!worst) continue;
		const title = safe(worst.goal.title, 60);
		const why = worst.goal.why?.trim();
		candidates.push({
			score: INTENT_WEIGHTS[intent] + (NUDGE_PACE[intent] - s.pace),
			message: {
				kind: "nudge",
				title: `${BURNER_LABELS[s.burner]} could use some heat`,
				body: why ? `"${title}" is behind. Why it matters: ${safe(why, 100)}` : `"${title}" is behind your pace. One small step today keeps it lit.`,
				url: `/#/burner/${s.burner}`,
				tag: "nudge",
				subject
			}
		});
	}
	for (const p of data.people) {
		if (p.deleted) continue;
		const intent = intentOf(p.burner);
		const threshold = PERSON_NUDGE_RATIO[intent];
		const cadence = Math.max(1, p.cadenceDays);
		const st = personStatus(p, data.touchpoints, today);
		const added = /^\d{4}-\d{2}-\d{2}/.test(p.createdAt) ? p.createdAt.slice(0, 10) : today;
		const days = st.daysSince ?? Math.max(0, diffDays(added, today));
		const ratio = days / cadence;
		if (ratio < threshold) continue;
		const subject = `person:${p.id}`;
		if (!cooledDown(nudged, subject, today, Math.max(7, Math.round(cadence / 2)))) continue;
		const name = safe(p.name, 40);
		const rhythm = cadenceLabel(cadence).toLowerCase();
		candidates.push({
			score: (intent === "low" ? 1.5 : 2.7) + Math.min(.25, (ratio - threshold) / 4),
			message: {
				kind: "nudge",
				title: `Reach out to ${name}?`,
				body: st.daysSince === null ? `No connection logged yet (your rhythm: ${rhythm}). A quick text counts.` : `${days} days since you last connected (your rhythm: ${rhythm}). A quick text counts.`,
				url: `/#/burner/${p.burner}`,
				tag: "nudge",
				subject
			}
		});
	}
	candidates.sort((a, b) => b.score - a.score);
	return candidates[0]?.message ?? null;
}
function pruneNudged(nudged, today) {
	const keep = addDays(today, -120);
	return Object.fromEntries(Object.entries(nudged ?? {}).filter(([, d]) => d >= keep));
}
const TEST_MESSAGE = {
	kind: "test",
	title: "Four Burners",
	body: "Notifications work on this device.",
	url: "/#/settings",
	tag: "test"
};
//#endregion
//#region src/server/notify/webpush.ts
const enc = new TextEncoder();
function b64urlEncode(bytes) {
	let s = "";
	for (const b of bytes) s += String.fromCharCode(b);
	return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function b64urlDecode(s) {
	const b64 = s.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(s.length / 4) * 4, "=");
	const bin = atob(b64);
	const out = new Uint8Array(bin.length);
	for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
	return out;
}
function concat(...parts) {
	const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
	let o = 0;
	for (const p of parts) {
		out.set(p, o);
		o += p.length;
	}
	return out;
}
async function hmac(key, data) {
	const k = await crypto.subtle.importKey("raw", key, {
		name: "HMAC",
		hash: "SHA-256"
	}, false, ["sign"]);
	return new Uint8Array(await crypto.subtle.sign("HMAC", k, data));
}
async function hkdf(salt, ikm, info, length) {
	return (await hmac(await hmac(salt, ikm), concat(info, new Uint8Array([1])))).slice(0, length);
}
function publicJwk(raw) {
	if (raw.length !== 65 || raw[0] !== 4) throw new Error("Expected an uncompressed P-256 public key.");
	return {
		kty: "EC",
		crv: "P-256",
		x: b64urlEncode(raw.slice(1, 33)),
		y: b64urlEncode(raw.slice(33, 65)),
		ext: true
	};
}
async function encryptPayload(sub, payload, opts = {}) {
	const uaPublic = b64urlDecode(sub.p256dh);
	const authSecret = b64urlDecode(sub.auth);
	if (authSecret.length < 16) throw new Error("The subscription auth secret is too short.");
	if (payload.length > 3800) throw new Error("Push payload too large.");
	const sender = opts.senderKeys ?? await crypto.subtle.generateKey({
		name: "ECDH",
		namedCurve: "P-256"
	}, true, ["deriveBits"]);
	const asPublic = new Uint8Array(await crypto.subtle.exportKey("raw", sender.publicKey));
	const uaKey = await crypto.subtle.importKey("jwk", publicJwk(uaPublic), {
		name: "ECDH",
		namedCurve: "P-256"
	}, false, []);
	const ikm = await hkdf(authSecret, new Uint8Array(await crypto.subtle.deriveBits({
		name: "ECDH",
		public: uaKey
	}, sender.privateKey, 256)), concat(enc.encode("WebPush: info\0"), uaPublic, asPublic), 32);
	const salt = opts.salt ?? crypto.getRandomValues(new Uint8Array(16));
	const cek = await hkdf(salt, ikm, enc.encode("Content-Encoding: aes128gcm\0"), 16);
	const nonce = await hkdf(salt, ikm, enc.encode("Content-Encoding: nonce\0"), 12);
	const plain = concat(payload, new Uint8Array([2]));
	const aes = await crypto.subtle.importKey("raw", cek, "AES-GCM", false, ["encrypt"]);
	const cipher = new Uint8Array(await crypto.subtle.encrypt({
		name: "AES-GCM",
		iv: nonce
	}, aes, plain));
	const header = new Uint8Array(21 + asPublic.length);
	header.set(salt, 0);
	new DataView(header.buffer).setUint32(16, 4096);
	header[20] = asPublic.length;
	header.set(asPublic, 21);
	return concat(header, cipher);
}
async function importVapidKey(keys) {
	const d = b64urlDecode(keys.privateKey);
	if (d.length !== 32) throw new Error("VAPID_PRIVATE_KEY must be a 32-byte base64url value.");
	const jwk = {
		...publicJwk(b64urlDecode(keys.publicKey)),
		d: b64urlEncode(d)
	};
	return crypto.subtle.importKey("jwk", jwk, {
		name: "ECDSA",
		namedCurve: "P-256"
	}, false, ["sign"]);
}
async function vapidAuthorization(endpoint, keys, signingKey, nowMs) {
	const claims = {
		aud: new URL(endpoint).origin,
		exp: Math.floor(nowMs / 1e3) + 43200,
		sub: keys.subject
	};
	const head = b64urlEncode(enc.encode(JSON.stringify({
		typ: "JWT",
		alg: "ES256"
	})));
	const body = b64urlEncode(enc.encode(JSON.stringify(claims)));
	return `vapid t=${head}.${body}.${b64urlEncode(new Uint8Array(await crypto.subtle.sign({
		name: "ECDSA",
		hash: "SHA-256"
	}, signingKey, enc.encode(`${head}.${body}`))))}, k=${keys.publicKey}`;
}
async function sendWebPush(sub, payload, keys, signingKey, fetchFn, nowMs, opts = {}) {
	let url;
	try {
		url = new URL(sub.endpoint);
	} catch {
		return {
			ok: false,
			status: 0,
			gone: true,
			reason: "Invalid endpoint"
		};
	}
	if (url.protocol !== "https:") return {
		ok: false,
		status: 0,
		gone: true,
		reason: "Endpoint is not https"
	};
	const body = await encryptPayload(sub, enc.encode(payload));
	const headers = {
		"Content-Type": "application/octet-stream",
		"Content-Encoding": "aes128gcm",
		TTL: String(opts.ttl ?? 14400),
		Urgency: opts.urgency ?? "normal",
		Authorization: await vapidAuthorization(sub.endpoint, keys, signingKey, nowMs)
	};
	if (opts.topic) headers.Topic = opts.topic.replace(/[^A-Za-z0-9_-]/g, "").slice(0, 32);
	let res;
	try {
		res = await fetchFn(url.toString(), {
			method: "POST",
			headers,
			body
		});
	} catch (e) {
		return {
			ok: false,
			status: 0,
			gone: false,
			reason: e instanceof Error ? e.message : "Network error"
		};
	}
	if (res.ok) return {
		ok: true,
		status: res.status
	};
	const text = (await res.text().catch(() => "")).slice(0, 200);
	return {
		ok: false,
		status: res.status,
		gone: res.status === 404 || res.status === 410,
		reason: text || res.statusText || `HTTP ${res.status}`
	};
}
//#endregion
//#region src/server/notify/handler.ts
const CORS = {
	"Access-Control-Allow-Origin": "*",
	"Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
	"Access-Control-Allow-Methods": "POST, OPTIONS"
};
function reply(status, body) {
	return new Response(JSON.stringify(body), {
		status,
		headers: {
			...CORS,
			"Content-Type": "application/json"
		}
	});
}
const GONE_KEEP_DAYS = 30;
async function deliver(deps, signingKey, subs, msg) {
	const at = deps.now().toISOString();
	const payload = JSON.stringify({
		title: msg.title,
		body: msg.body,
		url: msg.url,
		tag: msg.tag
	});
	const urgency = msg.kind === "nudge" ? "low" : "normal";
	return Promise.all(subs.map(async (s) => {
		const out = await sendWebPush(s, payload, deps.vapid, signingKey, deps.fetch, deps.now().getTime(), {
			topic: msg.tag,
			urgency
		});
		try {
			if (out.ok) await deps.store.markSent(s.endpoint, at);
			else if (out.gone) await deps.store.markGone(s.endpoint, at);
			else await deps.store.markError(s.endpoint, `${out.status}: ${out.reason}`, at);
		} catch (e) {
			deps.log?.(`record outcome failed: ${String(e)}`);
		}
		return {
			endpoint: s.endpoint,
			ok: out.ok,
			status: out.status
		};
	}));
}
async function runTick(deps) {
	const { store } = deps;
	const now = deps.now();
	const signingKey = await importVapidKey(deps.vapid);
	const subs = await store.subscriptions();
	const byUser = new Map();
	for (const s of subs) byUser.set(s.user_id, [...byUser.get(s.user_id) ?? [], s]);
	const summary = {
		accounts: byUser.size,
		sent: [],
		errors: 0
	};
	for (const [userId, devices] of byUser) try {
		const latest = [...devices].sort((a, b) => a.last_seen_at < b.last_seen_at ? 1 : -1)[0];
		const tz = isValidTimeZone(latest.time_zone) ? latest.time_zone : "UTC";
		const [settingsValue, state] = await Promise.all([store.settings(userId), store.state(userId)]);
		const settings = settingsOf(settingsValue);
		const due = dueNow(now, tz, settings, state);
		if (!due.daily && !due.weekly && !due.nudge) continue;
		const today = due.clock.localDate;
		const data = await store.data(userId, {
			quarterId: quarterOf(today).id,
			since: addDays(today, -400),
			reviewWeek: due.weekly ?? void 0
		});
		const send = async (msg) => {
			if (!msg) return;
			const results = await deliver(deps, signingKey, devices, msg);
			summary.sent.push({
				kind: msg.kind,
				devices: results.length,
				delivered: results.filter((r) => r.ok).length
			});
		};
		if (due.weekly && await store.claim(userId, "weekly_week", due.weekly)) await send(composeWeekly(data, due.weekly));
		if (due.daily && await store.claim(userId, "daily_date", today)) await send(composeDaily(data, settings, today));
		if (due.nudge && await store.claim(userId, "nudge_date", today)) {
			const nudge = pickNudge(data, settings, today, state.nudged);
			if (nudge?.subject) await store.saveNudged(userId, {
				...pruneNudged(state.nudged, today),
				[nudge.subject]: today
			});
			await send(nudge);
		}
	} catch (e) {
		summary.errors++;
		deps.log?.(`account run failed: ${e instanceof Error ? e.message : String(e)}`);
	}
	try {
		await store.pruneGone(new Date(now.getTime() - GONE_KEEP_DAYS * 864e5).toISOString());
	} catch (e) {
		deps.log?.(`prune failed: ${String(e)}`);
	}
	return summary;
}
async function sendTest(deps, userId, endpoint) {
	if (typeof endpoint !== "string" || !endpoint) return reply(400, { error: "endpoint required" });
	const sub = (await deps.store.subscriptions()).find((s) => s.endpoint === endpoint && s.user_id === userId);
	if (!sub) return reply(404, { error: "This device is not subscribed." });
	const [result] = await deliver(deps, await importVapidKey(deps.vapid), [sub], TEST_MESSAGE);
	return reply(200, result);
}
function createHandler(deps) {
	return async (req) => {
		if (req.method === "OPTIONS") return new Response(null, {
			status: 204,
			headers: CORS
		});
		if (req.method !== "POST") return reply(405, { error: "POST only" });
		try {
			const secret = req.headers.get("x-notify-secret");
			if (secret !== null) {
				if (!await deps.store.cronSecretOk(secret)) return reply(401, { error: "Bad schedule secret" });
				return reply(200, await runTick(deps));
			}
			const token = /^Bearer\s+(.+)$/i.exec(req.headers.get("authorization") ?? "")?.[1];
			const userId = token ? await deps.store.userFromToken(token) : null;
			if (!userId) return reply(401, { error: "Sign in required" });
			const body = await req.json().catch(() => ({}));
			if (body.action === "test") return await sendTest(deps, userId, body.endpoint);
			return reply(400, { error: "Unknown action" });
		} catch (e) {
			deps.log?.(`request failed: ${e instanceof Error ? e.message : String(e)}`);
			return reply(500, { error: "Server error" });
		}
	};
}
function readConfig(env) {
	const supabaseUrl = env("SUPABASE_URL");
	let serviceKey = env("NOTIFY_SERVICE_KEY");
	if (!serviceKey) try {
		const keys = JSON.parse(env("SUPABASE_SECRET_KEYS") ?? "{}");
		const k = keys.default ?? Object.values(keys)[0];
		if (typeof k === "string" && k) serviceKey = k;
	} catch {}
	serviceKey ||= env("SUPABASE_SERVICE_ROLE_KEY");
	const publicKey = env("VAPID_PUBLIC_KEY");
	const privateKey = env("VAPID_PRIVATE_KEY");
	const subject = env("VAPID_SUBJECT");
	const missing = [
		!supabaseUrl && "SUPABASE_URL",
		!serviceKey && "SUPABASE_SERVICE_ROLE_KEY",
		!publicKey && "VAPID_PUBLIC_KEY",
		!privateKey && "VAPID_PRIVATE_KEY",
		!subject && "VAPID_SUBJECT"
	].filter((x) => !!x);
	if (missing.length) return {
		ok: false,
		missing
	};
	return {
		ok: true,
		supabaseUrl,
		serviceKey,
		vapid: {
			publicKey,
			privateKey,
			subject
		}
	};
}
//#endregion
//#region src/server/notify/store.ts
var RestError = class extends Error {
	status;
	constructor(status, message) {
		super(message);
		this.status = status;
	}
};
const PAGE = 1e3;
function restStore(supabaseUrl, key, fetchFn) {
	const base = supabaseUrl.replace(/\/+$/, "");
	const headers = (extra = {}) => ({
		apikey: key,
		...key.startsWith("eyJ") ? { Authorization: `Bearer ${key}` } : {},
		...extra
	});
	async function call(path, init = {}) {
		const res = await fetchFn(`${base}${path}`, {
			...init,
			headers: {
				...headers(),
				...init.headers
			}
		});
		if (!res.ok) throw new RestError(res.status, `${init.method ?? "GET"} ${path.split("?")[0]}: HTTP ${res.status} ${(await res.text().catch(() => "")).slice(0, 200)}`);
		return res;
	}
	const json = async (path, init) => await (await call(path, init)).json();
	const q = (params) => new URLSearchParams(params).toString();
	const patch = (table, filter, body) => call(`/rest/v1/${table}?${q(filter)}`, {
		method: "PATCH",
		headers: {
			"Content-Type": "application/json",
			Prefer: "return=minimal"
		},
		body: JSON.stringify(body)
	});
	async function records(userId, collection, filters = {}) {
		const out = [];
		for (let offset = 0;; offset += PAGE) {
			const page = await json(`/rest/v1/records?${q({
				select: "data",
				user_id: `eq.${userId}`,
				collection: `eq.${collection}`,
				deleted: "is.false",
				...filters,
				order: "id",
				limit: String(PAGE),
				offset: String(offset)
			})}`);
			out.push(...page.map((r) => r.data));
			if (page.length < PAGE) return out;
		}
	}
	return {
		async cronSecretOk(secret) {
			return await json("/rest/v1/rpc/notify_cron_ok", {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ p_secret: secret })
			}) === true;
		},
		async userFromToken(token) {
			const res = await fetchFn(`${base}/auth/v1/user`, { headers: {
				apikey: key,
				Authorization: `Bearer ${token}`
			} });
			if (!res.ok) return null;
			const user = await res.json().catch(() => null);
			return typeof user?.id === "string" ? user.id : null;
		},
		subscriptions: () => json(`/rest/v1/push_subscriptions?${q({
			select: "endpoint,user_id,p256dh,auth,device,time_zone,last_seen_at",
			gone_at: "is.null",
			order: "user_id,last_seen_at.desc"
		})}`),
		async state(userId) {
			const r = (await json(`/rest/v1/push_state?${q({
				select: "daily_date,weekly_week,nudge_date,nudged",
				user_id: `eq.${userId}`
			})}`))[0];
			return r ? {
				dailyDate: r.daily_date ?? void 0,
				weeklyWeek: r.weekly_week ?? void 0,
				nudgeDate: r.nudge_date ?? void 0,
				nudged: r.nudged ?? {}
			} : {};
		},
		async claim(userId, field, value) {
			await call("/rest/v1/push_state?on_conflict=user_id", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
					Prefer: "resolution=ignore-duplicates,return=minimal"
				},
				body: JSON.stringify({ user_id: userId })
			});
			return (await json(`/rest/v1/push_state?${q({
				user_id: `eq.${userId}`,
				or: `(${field}.is.null,${field}.neq.${value})`
			})}`, {
				method: "PATCH",
				headers: {
					"Content-Type": "application/json",
					Prefer: "return=representation"
				},
				body: JSON.stringify({
					[field]: value,
					updated_at: new Date().toISOString()
				})
			})).length === 1;
		},
		async saveNudged(userId, nudged) {
			await patch("push_state", { user_id: `eq.${userId}` }, {
				nudged,
				updated_at: new Date().toISOString()
			});
		},
		async settings(userId) {
			return (await json(`/rest/v1/records?${q({
				select: "data",
				user_id: `eq.${userId}`,
				collection: "eq.kv",
				id: "eq.settings",
				deleted: "is.false"
			})}`))[0]?.data?.value;
		},
		async data(userId, req) {
			const since = { "data->>localDate": `gte.${req.since}` };
			const [quarters, goals, logs, energy, people, touchpoints, crunch, actions, reviews] = await Promise.all([
				records(userId, "quarters", { id: `eq.${req.quarterId}` }),
				records(userId, "goals", { "data->>quarterId": `eq.${req.quarterId}` }),
				records(userId, "logs", since),
				records(userId, "energy", since),
				records(userId, "people"),
				records(userId, "touchpoints"),
				records(userId, "crunch"),
				records(userId, "actions", { "data->>weekStart": `gte.${req.since}` }),
				req.reviewWeek ? records(userId, "reviews", { id: `eq.review-${req.reviewWeek}` }) : Promise.resolve([])
			]);
			return {
				quarter: quarters[0],
				goals,
				logs,
				energy,
				people,
				touchpoints,
				crunch,
				actions,
				reviews
			};
		},
		async markSent(endpoint, at) {
			await patch("push_subscriptions", { endpoint: `eq.${endpoint}` }, {
				last_sent_at: at,
				last_error: null,
				last_error_at: null
			});
		},
		async markError(endpoint, reason, at) {
			await patch("push_subscriptions", { endpoint: `eq.${endpoint}` }, {
				last_error: reason.slice(0, 300),
				last_error_at: at
			});
		},
		async markGone(endpoint, at) {
			await patch("push_subscriptions", { endpoint: `eq.${endpoint}` }, { gone_at: at });
		},
		async pruneGone(before) {
			await call(`/rest/v1/push_subscriptions?${q({ gone_at: `lt.${before}` })}`, {
				method: "DELETE",
				headers: { Prefer: "return=minimal" }
			});
		}
	};
}
//#endregion
//#region src/server/notify/entry.deno.ts
const config = readConfig((name) => Deno.env.get(name));
Deno.serve(config.ok ? createHandler({
	store: restStore(config.supabaseUrl, config.serviceKey, fetch),
	vapid: config.vapid,
	fetch,
	now: () => new Date(),
	log: (msg) => console.error(msg)
}) : async () => new Response(JSON.stringify({
	error: "The notify function is missing secrets.",
	missing: config.missing
}), {
	status: 500,
	headers: { "Content-Type": "application/json" }
}));
//#endregion
